#!/usr/bin/env bash
# ============================================================================
# PVM Env Manager - Lockfile merge conflict resolver (Unix)
# ============================================================================
# Auto-resolve conflicts in lock files (pnpm-lock.yaml / package-lock.json / yarn.lock)
# These files are auto-generated by package managers; manual merging is error-prone.
#
# Strategy:
#   1. git checkout --theirs  (take remote version to clear conflict markers)
#   2. pnpm install --lockfile-only  (regenerate lockfile from local package.json)
#   3. git add  (stage the regenerated lockfile)
#
# Usage: ./resolve-lockfile-conflict.sh [--regenerate|--no-regenerate]
#   --regenerate     : (default) clear conflict + regenerate from local package.json
#   --no-regenerate : only clear conflict markers, keep remote version
# ============================================================================

set -euo pipefail

echo "========================================"
echo "  Lockfile Merge Conflict Resolver"
echo "========================================"
echo ""

# Check if inside a git repo
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "[ERROR] Not a Git repository"
    exit 1
fi

# Parse arguments
DO_REGENERATE=1
FOUND_PNPM=0
FOUND_NPM=0
FOUND_YARN=0

case "${1:-}" in
    --no-regenerate) DO_REGENERATE=0 ;;
    --regenerate)    DO_REGENERATE=1 ;;
esac

# Collect conflicting files
CONFLICT_COUNT=0
LOCKFILE_COUNT=0

while IFS= read -r file; do
    CONFLICT_COUNT=$((CONFLICT_COUNT + 1))

    # Check if it's a lock file
    if echo "$file" | grep -qiE '(pnpm-lock\.yaml|package-lock\.json|yarn\.lock)'; then
        LOCKFILE_COUNT=$((LOCKFILE_COUNT + 1))
        echo "[FOUND] $file"

        # Determine which lock type
        if echo "$file" | grep -qi 'pnpm-lock\.yaml'; then FOUND_PNPM=1; fi
        if echo "$file" | grep -qi 'package-lock\.json'; then FOUND_NPM=1; fi
        if echo "$file" | grep -qi 'yarn\.lock'; then FOUND_YARN=1; fi

        # Resolve: checkout --theirs
        echo "[ACTION] $file -> git checkout --theirs"
        git checkout --theirs -- "$file" 2>&1 || {
            echo "[ERROR] Failed to checkout --theirs for $file"
            exit 1
        }
        echo "[OK] Conflict markers cleared"

        # Stage immediately so conflict is marked resolved in the index
        git add "$file"
    fi
done < <(git diff --name-only --diff-filter=U 2>/dev/null)

echo ""
echo "========================================"
echo "  Results"
echo "========================================"
echo "Total conflicts:   $CONFLICT_COUNT"
echo "Lockfile conflicts: $LOCKFILE_COUNT"
echo ""

if [ "$LOCKFILE_COUNT" -eq 0 ]; then
    if [ "$CONFLICT_COUNT" -eq 0 ]; then
        echo "[INFO] No merge conflicts found"
    else
        echo "[INFO] No lockfile conflicts found (other conflicts need manual merge)"
    fi
    exit 0
fi

# Regenerate lockfiles after resolving all conflicts
if [ "$DO_REGENERATE" -eq 1 ]; then
    echo ""
    echo "[REGENERATE] Regenerating lockfile..."
    echo ""

    if [ "$FOUND_PNPM" -eq 1 ]; then
        echo "Detected pnpm-lock.yaml"
        if pnpm install --lockfile-only --no-frozen-lockfile 2>&1; then
            echo "[OK] pnpm install succeeded"
            if [ -f pnpm-lock.yaml ]; then git add pnpm-lock.yaml; fi
        else
            echo "[ERROR] pnpm install failed, lockfile may be inconsistent"
            echo "[HINT] Try: pnpm install"
        fi
        if [ -f node_modules/.modules.yaml ]; then git add node_modules/.modules.yaml; fi
    fi

    if [ "$FOUND_NPM" -eq 1 ]; then
        echo "Detected package-lock.json"
        if npm install --package-lock-only 2>&1; then
            echo "[OK] npm install succeeded"
            if [ -f package-lock.json ]; then git add package-lock.json; fi
        else
            echo "[ERROR] npm install failed"
        fi
    fi

    if [ "$FOUND_YARN" -eq 1 ]; then
        echo "Detected yarn.lock"
        if yarn install --mode update-lockfile 2>&1; then
            echo "[OK] yarn install succeeded"
            if [ -f yarn.lock ]; then git add yarn.lock; fi
        else
            echo "[ERROR] yarn install failed"
        fi
    fi
fi

echo ""
echo "[DONE] Resolved $LOCKFILE_COUNT lockfile conflict(s)"
