@echo off
REM ============================================================================
REM PVM Env Manager - Lockfile merge conflict resolver (Windows)
REM ============================================================================
REM Auto-resolve conflicts in lock files (pnpm-lock.yaml / package-lock.json / yarn.lock)
REM These files are auto-generated by package managers; manual merging is error-prone.
REM
REM Strategy:
REM   1. git checkout --theirs  (take remote version to clear conflict markers)
REM   2. pnpm install --lockfile-only  (regenerate lockfile from local package.json)
REM   3. git add  (stage the regenerated lockfile)
REM
REM Usage: resolve-lockfile-conflict.bat [--regenerate|--no-regenerate]
REM   --regenerate     : (default) clear conflict + regenerate from local package.json
REM   --no-regenerate : only clear conflict markers, keep remote version
REM ============================================================================

chcp 65001 >nul 2>&1

setlocal enabledelayedexpansion

echo ========================================
echo   Lockfile Merge Conflict Resolver
echo ========================================
echo.

REM Check if inside a git repo
git rev-parse --is-inside-work-tree >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Not a Git repository
    exit /b 1
)

REM Parse arguments
set DO_REGENERATE=1
if "%~1"=="--no-regenerate" set DO_REGENERATE=0
if "%~1"=="--regenerate" set DO_REGENERATE=1

REM Collect conflicting files
set "TMP_FILE=%CD%\._pvm_conflict.tmp"
git diff --name-only --diff-filter=U > "%TMP_FILE%" 2>nul

set CONFLICT_COUNT=0
set LOCKFILE_COUNT=0
set FOUND_PNPM=0
set FOUND_NPM=0
set FOUND_YARN=0

if exist "%TMP_FILE%" (
    for /f "usebackq tokens=*" %%f in ("%TMP_FILE%") do (
        set /a CONFLICT_COUNT+=1
        set "name=%%f"

        call :is_lockfile "!name!"
        if !errorlevel!==0 (
            set /a LOCKFILE_COUNT+=1
            echo [FOUND] !name!
            call :resolve "!name!"
        )
    )
    del "%TMP_FILE%" 2>nul
)

echo.
echo ========================================
echo   Results
echo ========================================
echo Total conflicts:   !CONFLICT_COUNT!
echo Lockfile conflicts: !LOCKFILE_COUNT!
echo.

if !LOCKFILE_COUNT!==0 (
    if !CONFLICT_COUNT!==0 (
        echo [INFO] No merge conflicts found
    ) else (
        echo [INFO] No lockfile conflicts found ^(other conflicts need manual merge^)
    )
    exit /b 0
)

REM Regenerate lockfiles after resolving all conflicts
if !DO_REGENERATE!==1 (
    echo.
    echo [REGENERATE] Running pnpm install --lockfile-only ...
    echo.

    REM Remove possibly stale node_modules to force clean resolve
    REM (uncomment if needed):
    REM if exist node_modules rmdir /s /q node_modules

    if !FOUND_PNPM!==1 (
        echo Detected pnpm-lock.yaml
        pnpm install --lockfile-only --no-frozen-lockfile 2>&1
        if !errorlevel!==0 (
            echo [OK] pnpm install succeeded
            if exist pnpm-lock.yaml git add pnpm-lock.yaml
        ) else (
            echo [ERROR] pnpm install failed, lockfile may be inconsistent
            echo [HINT] Try: pnpm install
        )
        if exist node_modules\.modules.yaml git add node_modules\.modules.yaml
    )

    if !FOUND_NPM!==1 (
        echo Detected package-lock.json
        npm install --package-lock-only 2>&1
        if !errorlevel!==0 (
            echo [OK] npm install succeeded
            if exist package-lock.json git add package-lock.json
        ) else (
            echo [ERROR] npm install failed
        )
    )

    if !FOUND_YARN!==1 (
        echo Detected yarn.lock
        yarn install --mode update-lockfile 2>&1
        if !errorlevel!==0 (
            echo [OK] yarn install succeeded
            if exist yarn.lock git add yarn.lock
        ) else (
            echo [ERROR] yarn install failed
        )
    )
)

echo.
echo [DONE] Resolved !LOCKFILE_COUNT! lockfile conflict(s)
exit /b 0

REM ============================================================================
REM Check if a file is a lock file
REM ============================================================================
:is_lockfile
set "name=%~1"
echo !name! | findstr /i /c:"pnpm-lock.yaml" >nul
if !errorlevel!==0 (set FOUND_PNPM=1 & exit /b 0)
echo !name! | findstr /i /c:"package-lock.json" >nul
if !errorlevel!==0 (set FOUND_NPM=1 & exit /b 0)
echo !name! | findstr /i /c:"yarn.lock" >nul
if !errorlevel!==0 (set FOUND_YARN=1 & exit /b 0)
exit /b 1

REM ============================================================================
REM Resolve a single lockfile conflict
REM ============================================================================
:resolve
set "target=%~1"

echo [ACTION] !target! -^> git checkout --theirs
git checkout --theirs "!target!" 2>&1
if errorlevel 1 (
    echo [ERROR] Failed to checkout --theirs for !target!
    exit /b 1
)
echo [OK] Conflict markers cleared

REM Stage immediately so conflict is marked resolved in the index.
REM The eventual pnpm install may modify the file again, so we re-add after that too.
git add "!target!"

exit /b 0
