package ssh

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SSHConfigEntry SSH config 配置项
type SSHConfigEntry struct {
	Host    string
	Options map[string]string
}

// SSHConfigManager SSH config 管理器
type SSHConfigManager struct {
	ConfigPath string
}

// NewSSHConfigManager 创建 SSH config 管理器
func NewSSHConfigManager() *SSHConfigManager {
	sshDir := DefaultSSHDir()
	return &SSHConfigManager{
		ConfigPath: filepath.Join(sshDir, "config"),
	}
}

// AddHostConfig 添加或更新 Host 配置
func (m *SSHConfigManager) AddHostConfig(entry *SSHConfigEntry) error {
	// 确保 .ssh 目录存在
	sshDir := filepath.Dir(m.ConfigPath)
	if err := os.MkdirAll(sshDir, 0700); err != nil {
		return fmt.Errorf("failed to create .ssh directory: %w", err)
	}

	// 读取现有配置
	existingEntries, err := m.ReadConfig()
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to read existing config: %w", err)
	}

	// 查找是否已存在相同 Host
	found := false
	for i, e := range existingEntries {
		if e.Host == entry.Host {
			// 合并配置
			for k, v := range entry.Options {
				existingEntries[i].Options[k] = v
			}
			found = true
			break
		}
	}

	if !found {
		existingEntries = append(existingEntries, entry)
	}

	// 写入配置
	return m.WriteConfig(existingEntries)
}

// ReadConfig 读取 SSH config
func (m *SSHConfigManager) ReadConfig() ([]*SSHConfigEntry, error) {
	if _, err := os.Stat(m.ConfigPath); os.IsNotExist(err) {
		return nil, nil
	}

	file, err := os.Open(m.ConfigPath)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var entries []*SSHConfigEntry
	var currentEntry *SSHConfigEntry

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// 跳过空行和注释
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// 解析 Host 行
		if strings.HasPrefix(line, "Host ") {
			if currentEntry != nil {
				entries = append(entries, currentEntry)
			}
			host := strings.TrimPrefix(line, "Host ")
			host = strings.TrimSpace(host)
			currentEntry = &SSHConfigEntry{
				Host:    host,
				Options: make(map[string]string),
			}
			continue
		}

		// 解析配置项
		if currentEntry != nil {
			parts := strings.SplitN(line, " ", 2)
			if len(parts) == 2 {
				key := strings.TrimSpace(parts[0])
				value := strings.TrimSpace(parts[1])
				currentEntry.Options[key] = value
			}
		}
	}

	if currentEntry != nil {
		entries = append(entries, currentEntry)
	}

	return entries, scanner.Err()
}

// WriteConfig 写入 SSH config
func (m *SSHConfigManager) WriteConfig(entries []*SSHConfigEntry) error {
	var lines []string
	lines = append(lines, "# SSH config generated by pvm")
	lines = append(lines, "# https://github.com/pvm/pvm")
	lines = append(lines, "")

	for _, entry := range entries {
		lines = append(lines, fmt.Sprintf("Host %s", entry.Host))
		for key, value := range entry.Options {
			lines = append(lines, fmt.Sprintf("    %s %s", key, value))
		}
		lines = append(lines, "")
	}

	content := strings.Join(lines, "\n")
	return os.WriteFile(m.ConfigPath, []byte(content), 0600)
}

// GenerateDefaultHostConfig 生成默认 Host 配置
func GenerateDefaultHostConfig(platform Platform, customURL string) *SSHConfigEntry {
	var host string
	var options map[string]string

	switch platform {
	case PlatformGitHub:
		host = "github.com"
		options = map[string]string{
			"HostName":          "github.com",
			"User":              "git",
			"IdentityFile":      "~/.ssh/id_rsa",
			"PreferredAuthentications": "publickey",
		}
	case PlatformGitLab:
		if customURL != "" {
			host = ExtractHostFromURL(customURL)
		} else {
			host = "gitlab.com"
		}
		options = map[string]string{
			"HostName":          host,
			"User":              "git",
			"IdentityFile":      "~/.ssh/id_rsa",
			"PreferredAuthentications": "publickey",
		}
	case PlatformGitee:
		host = "gitee.com"
		options = map[string]string{
			"HostName":          "gitee.com",
			"User":              "git",
			"IdentityFile":      "~/.ssh/id_rsa",
			"PreferredAuthentications": "publickey",
		}
	case PlatformCustom:
		host = ExtractHostFromURL(customURL)
		options = map[string]string{
			"HostName":          host,
			"User":              "git",
			"IdentityFile":      "~/.ssh/id_rsa",
			"PreferredAuthentications": "publickey",
		}
	}

	return &SSHConfigEntry{
		Host:    host,
		Options: options,
	}
}

// RemoveHostConfig 移除 Host 配置
func (m *SSHConfigManager) RemoveHostConfig(host string) error {
	entries, err := m.ReadConfig()
	if err != nil {
		return err
	}

	var newEntries []*SSHConfigEntry
	for _, e := range entries {
		if e.Host != host {
			newEntries = append(newEntries, e)
		}
	}

	return m.WriteConfig(newEntries)
}